# 服务器配置
server:
  # servlet配置
  servlet:
    context-path: /member # 应用的上下文路径，用于区分不同的Web应用
  port: 8001 # 服务器监听的端口，决定应用通过哪个端口接收请求

# Spring应用配置
spring:
  application:
    name: member # 应用名称，用于标识和区分不同的Spring Boot应用
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名，指定连接MySQL数据库所需的驱动类
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai # 数据库连接URL，包括数据库地址、端口、数据库名称等信息
    username: root  # 数据库用户名，用于登录数据库
    password: wxz123456  # 数据库密码，配合用户名使用以验证登录身份

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定Mapper XML文件的位置，MyBatis根据此配置找到SQL映射文件进行SQL查询的定义
logging:
  level:
    com.wxz.train.member.mapper : trace # 日志级别配置，针对com.wxz.train.member.mapper包下的日志记录级别设定为trace，以便详细记录操作信息
