POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "memberId": "1",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "memberId": "1",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "wnknsa",
  "idCard": "123327",
  "type": "1"
}

###
GET http://localhost:8001/member/passenger/query-list
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1768293540707831808,
  "memberId": 1767241446253006848,
  "name": "neil测试1",
  "idCard": "11111111111111111",
  "type": "1",
  "createTime": "2024-03-14 23:10:08"
}

###
DELETE http://localhost:8000/member/passenger/delete/1788219369780809728
Accept: application/json
token: {{token}}

###

